server:
  port: 8021

spring:
  application:
    name: service2

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # ??? ???? (???) ?? ??
    fetch-registry: true
    registryFetchIntervalSeconds: 5 # eureka?? ??? ??? ???? ??
    disable-delta: true # eureka?? ??? ??? ???? ??? ??? ????. (false? ?? ??? ????? ??? ????.)
